#!/usr/bin/env Rscript
# Author: Tao Xiong
# Date: 2025-05-13
# Description: 

# ==== Main Script Start ====


setwd("E:/R/R_plot/Fabaceae/BAMM/BAMM_2025.04.09")

rm(list=ls())
# install.packages("BiocManager")

# install.packages("BAMMtools")
library(ape)
library("BAMMtools")
library("coda")
# BiocManager::install("treeio")
library(treeio)
# BiocManager::install("ggtree")
library(ggtree)
# install.packages("ggplot2")
library(ggplot2)
library("RPANDA")
library("scales")
library(phytools)

# assuming event data and mcmc out files generated by BAMM
# are store under folder named by each of 17 orders
# e.g. "working_dir/Rosales/Rosales_event_data_final.txt"
# e.g. "working_dir/Rosales/Rosales_mcmc_out_final.txt"



if(!dir.exists("./results")){
  dir.create("./results")
} 


Fab <- read.tree("./Fabaceae_date6.update.471genera.20250327.tre")
new_fab <- ladderize(Fab,right = F)
plot(new_fab)


#检测结果是否收敛
#以图像的形式检测，最终拟合的线性越好，收敛的越好
#Assessing MCMC convergence
mcmc <- read.csv("./BAMM_Fab_Fab_mcmc_out.txt", header=T)

pdf("./results/Fabaceae_MCMC_convergent.pdf",width = 12,height = 8)
plot(mcmc$logLik ~ mcmc$generation)
dev.off()


burnstart <- floor(0.1*nrow(mcmc)) #discard the top 10% of data
postburn <- mcmc[burnstart:nrow(mcmc), ]#postburn is the generations left after burning

#以数值的方式检测，最终的有效样本量即N_shift高于200为收敛良好
#next caculate the effective sample size (ESS), which should be greater than 200 if our analysis
# ran long enough
logLik <- effectiveSize(postburn$logLik) # calculates autocorrelation function
N_shift <- effectiveSize(postburn$N_shift) #effective sample size on N-shifts
ESSample <- cbind.data.frame("Fabaceae", logLik, N_shift)


write.table(ESSample, paste("./results/", "Fabaceae", "_ESS_convergence.txt"), row.names=F, quote=F, append=T, sep="\t")


#收敛结果判断为良好后开始整理结果
#BAMM object
edata <- getEventData(new_fab, eventdata = "./BAMM_Fab_Fab_event_data.txt", burnin = 0.10)

summary(edata)
saveRDS(edata, file=paste("./results/Fabaceae_edata.rds", sep=""))

edata <- readRDS("./results/Fabaceae_edata.rds")

# #数据太大的话可以先在服务器中读入后再直接读取rds文件
# edata <- readRDS("./bamm_08.28_24/sp/Fabaceae_edata.rds")
# 
# #tip rates
# TR <- getTipRates(edata, returnNetDiv = FALSE, statistic = "median")
# file <- paste0("./results/", "Fabaceae", "_BAMM_TipRates.csv", sep="")
# cat("Tip_label,Rate\n", file=file)
# write.table(TR$lambda.avg, sep=",", file=file, col.names = FALSE, quote=FALSE, append = TRUE)
# 
# ##### Prepare Mean Rate Matrix ####
rtt <- getRateThroughTimeMatrix(edata)
rtt <- readRDS("./results/Fabaceae_RateThroughTimeMatrix.rds")
# Mean.lamda <- apply(rtt$lambda, 2, quantile,c(0.5))
# Mean.mu <- apply(rtt$mu, 2, quantile, c(0.5))
# mean.netdiv <- Mean.lamda - Mean.mu
# 
# Mean.Rate.Matrix <- cbind.data.frame(rtt$times, Mean.lamda, Mean.mu, mean.netdiv)
# write.csv(Mean.Rate.Matrix, paste("./results/", "Fabaceae", "_Mean_Rate_Matrix.csv", sep=""), row.names = FALSE, quote=FALSE)
# 
# saveRDS(rtt, paste("./results/Fabaceae_RateThroughTimeMatrix.rds", sep=""))

# 
# #输出净多样化速率曲线
# pdf("./bamm_08.28_24/genus/result/Fabaceae_netdiv.pdf",width=9,height = 6)
# plotRateThroughTime(rtt, ratetype = "netdiv", useMedian=TRUE, lwd=2, avgCol="orange", smooth=TRUE, cex.lab = 1, xline=2, yline=2.5, cex.axis=1)
# dev.off()
# 
# 
# #输出灭绝速率曲线
# pdf("./bamm_08.28_24/genus/result/Fabaceae_extinction.pdf",width=9,height = 6)
# plotRateThroughTime(rtt, ratetype = "extinction", useMedian=TRUE, lwd=2, avgCol="blue", smooth=TRUE, cex.lab = 1, xline=2, yline=2.8, cex.axis=1)
# dev.off()


####################  给系统发育树标注属级分类  ############################


#给系统发育属标注属级分类
#数据处理，标注好书上各个分支对应的亚科

tipname <- as.data.frame(new_fab$tip.label)
colnames(tipname) <- "taxon_name"
tipname$taxon_name <- sub("(.*)_.*", "\\1", tipname$taxon_name)
tipname$taxon_name <- gsub("_GCA", "", tipname$taxon_name)

new_fab$tip.label <- sub("(.*)_.*", "\\1", new_fab$tip.label)
new_fab$tip.label <- gsub("_GCA", "", new_fab$tip.label)


subname <- read.csv("Fabaceae_subfam.wcvp.accepted_240521.csv")
subname$taxon_name <- gsub(" ", "_", subname$taxon_name)

tip_subname <- merge(tipname,subname,by="taxon_name",all.x = T)
#write.csv(tip_subname,"tip_subname.csv")
# tip_subname <- read.csv("tip_subname.csv")

#生成分组文件
group_file <- tip_subname[,c("taxon_name","subfamily")]
colnames(group_file) <- c("taxon_name","subfamily")
# group_file$genus <- gsub(" ", "_", group_file$genus)

write.csv(group_file,"group_file.csv")

#写出再重新读入，我也不知为啥要这样
group_file <- read.csv("group_file.csv",header = T,row.names = 1)

# 按类分组
groupInfo <- split(row.names(group_file), group_file$subfamily)

# 将分组信息添加到树中
Fab <- groupOTU(new_fab, groupInfo)

df4 <- as.data.frame(tip_subname$subfamily)
rownames(df4) <- gsub(" ","_",tip_subname$taxon_name)

circ <- ggtree(Fab, size=1,layout="re", ladderize = FALSE) +
  # geom_tiplab(fontface=3,size=6.5,offset= 0)+
  geom_text(aes(label=node),size=2,hjust=-1)
 # scale_color_manual(values = c("#A9A9A9","#f58231"),labels = c("临沧市维管植物","云县维管植物"))+
  theme(legend.position = "right",
        legend.title = element_blank(),
        legend.key.size = unit(5, "cm"),
        legend.text = element_text(size=100))
 
#   tree_fab <- extract.clade(Fab,node=1014)
#   plot(tree_fab)
# 
# circ
  
pdf("./results/Fabaceae_tree_groups.pdf", height = 30, width = 25)
col1 <- c("#DC143C","#9400D3","#7B68EE","#0000FF","#48D1CC","#00FF7F","#FFFF00")
gheatmap(circ, df4, offset=1, width=0.03,colnames = F) +
  scale_fill_manual(values = col1)+
  theme(legend.position = c(0.15,0.9),
        legend.title = element_blank(),
        legend.key.size = unit(40, "pt"),
        legend.text = element_text(size=20))
dev.off()





############
###Plot rates
library("scales")
source("../data/plotRateThroughTime_function_modified.R")
#Tm data
InfTemp <- read.csv("../data/Global_paleo-temperature.csv", header = TRUE)
smoothingSpline <-  smooth.spline(InfTemp$Temp_C ~ InfTemp$Age, spar=0.35)

#new_tm
tm <- read.table("temperature.txt",header = T)
smoothingSpline_tm <-  smooth.spline(tm$Temperature ~ tm$Age, spar=0.35)

# CO2 
data(co2)
CO2 <- co2
smoothingSpline_co2 <-  smooth.spline(CO2$co2 ~ CO2$age , spar=0.35)

#new_co2
cc <- read.table("CO2_combined_70Ma.txt",header = T)
smoothingSpline_cc <-  smooth.spline(cc$CO2 ~ cc$Age , spar=0.35)
# 
# #remove outlior function
# outlier <- function(x) {
#   xx <- x[!x %in% boxplot.stats(x)$out]
#   return(xx)
# }
# 
# #BAMM event data
# rate_matrix <- readRDS("./bamm_08.28_24/genus/Fabaceae_RateThroughTimeMatrix.rds")
# coll <- c("black", "cyan4", "deeppink",  "blue", "darkorange")
# inter.cc <- "gray70"
# 
# #输出多样化转化图并标定转化点
# pdf("./bamm_08.28_24/sp/result/diversity_shift.pdf",width = 25,height = 30)
# par(new=F, mgp = c(0, 1, 2),oma=c(2,2,2,2))
# plot(smoothingSpline, col='#c04851', axes = F, xlim=c(max(rtt$times),0), type = "l",lty=5,lwd=3, xlab="", ylab="",alpha=0.7)
# axis(1, line=0, cex.axis=2)
# axis(2, line=0, cex.axis=2)
# mtext("Temperature (°C)", line=3.5, side=2, cex=3)
# mtext("Time before present (Myr)",line=3.5,side=1,cex=3)
# par(new=TRUE, mgp = c(0, 1, 0))
# plot.bammdata(edata, lwd=2.5, labels=F,pal="RdYlGn")
# addBAMMshifts(edata,cex = 2.5)
# dev.off()






pdf("./bamm_08.28_24/sp/result/Fabaceae_LTT_with_TM_Co2.pdf", height = 12, width = 16)
# aa <- outlier(rtt$lambda-rtt$mu)
#plot Temperature change rate
plot(smoothingSpline_tm, col='skyblue', axes = F, xlim=c(max(rtt$times),0), type = "l", lty = 5,lwd=2, xlab="", ylab="")
axis(4, line=-1,tck=-0.01, cex.axis=0.9,mgp = c(1, 0.2, 0))
mtext("Temperature (°C)", line=-2.5, side=4, cex=1.1)
par(new=TRUE, mgp = c(0, 0.6, 0))
# plot CO2 change rate
# plot(smoothingSpline_co2, col='orange', axes = F, xlim=c(max(rtt$times),0), type = "l", lty = 5,lwd=2, xlab="", ylab="")
# axis(4, line=1.5,tck=-0.01, cex.axis=0.9,mgp = c(1, 0.2, 0))
# mtext("CO2", line=-2.5, side=4, cex=1.1)
# par(new=TRUE, mgp = c(0, 0.6, 0))
plot(smoothingSpline_co2, col='orange', axes = F, xlim=c(max(rtt$times),0), type = "l", lty = 5,lwd=2, xlab="", ylab="")
#plot speciation rate
par(new=TRUE, mgp = c(0, 0.6, 0))
plotRateThroughTime(rtt,ratetype = "speciation",axis = F,ylim=c(0,0.4), useMedian=TRUE, lwd=2, avgCol="deeppink",intervalCol="deeppink",smooth=TRUE, cex.lab = 1, xline=3, yline=2.8,cex.axis = 1)
par(new=TRUE, mgp = c(0, 0.6, 0))
#plot netdiv rate
plotRateThroughTime(rtt,axis.labels = F,ratetype = "netdiv", ylim=c(0,0.4) , useMedian=TRUE,lwd=2, intervalCol="gray70", avgCol=coll[1], smooth=TRUE, cex.lab = 1.3, xline=2.2, yline=3.2, cex.axis=1)
par(new=TRUE, mgp = c(0, 0.6, 0))
#plot extinction rate
plotRateThroughTime(rtt, ratetype = "extinction",axis = F,ylim=c(0,0.4), useMedian=TRUE, lwd=2, avgCol="blue", intervalCol="blue",smooth=TRUE, cex.lab = 1, xline=2, yline=2.8, cex.axis=1)
par(new=TRUE, mgp = c(0, 0.6, 0))
mtext(expression("Diversification rate (Myr"^"-1"*")"), line=2.5, side=2, cex=1.3)    
mtext("Time before present (Myr)", line=2.5, side=1, cex=1.3) 
legend(22,0.4,bty="n", legend = c("Speciation rate", "Netdiv rate","Extinction rate","Temperature","CO2"), col = c("deeppink", "black","blue","skyblue","orange"),lty = c(1,1,1,2,2),lwd = 2)
dev.off()







#======================= best diversification shift point ===================================
edata <- readRDS(file = "./Fab_edata2.rds")
plotRateThroughTime(rtt,ratetype = "speciation")

#Tm data
InfTemp <- read.csv("./env_data/temperature-0.5ma-FABIEN-approx-70(1).csv", header = TRUE)
smoothingSpline_tm <-  smooth.spline(InfTemp$Temperature ~ InfTemp$Age, spar=0.35)

#CO2 data
Infco2 <- read.table("./env_data/500kyrCO2_combined_70Ma.txt", header = TRUE)
smoothingSpline_co2 <-  smooth.spline(Infco2$CO2 ~ Infco2$Age, spar=0.35)




###plot diversification shifts
plot.bammdata(edata, method="polar",lwd=2.5,pal="RdYlGn")
addBAMMshifts(edata,method="polar",cex = 2.5)
best <- getBestShiftConfiguration(edata, expectedNumberOfShifts=1, threshold=5)


pdf("./results/Fabaceae_best_diversification_shift_netdiv_tm_co2.pdf", height = 30, width = 30)
par(new=T, mgp = c(0, 2, 2),oma=c(3,15,3,5))
plot(smoothingSpline_tm, col='#FF0000', axes = F, xlim=c(max(rtt$times),0), type = "l",lty=5,lwd=4, xlab="", ylab="",alpha=0.7)
axis(2,at=seq(-1, 2, by=1), labels=round(seq(-1, 2, by=1), 1), line=0, cex.axis=3)
mtext("CO2", line=14, side=2, cex=3.8)
par(new=T, mgp = c(0, 2, 2),oma=c(3,15,3,5))
plot(smoothingSpline_co2, col='black', axes = F, xlim=c(max(rtt$times),0), type = "l",lty=5,lwd=4, xlab="", ylab="",alpha=0.7)
axis(2,at=seq(-1, 2, by=1), labels=round(seq(-1, 2, by=1), 1), line=10, cex.axis=3)
axis(1, line=0, cex.axis=3,padj = 0.4)
title(main = "Best Diversification Shifts (netdiv)", font.main = 1, cex.main = 3)
mtext("Temperature (°C)", line=5, side=2, cex=3.8,col="red")
mtext("Time before present (Myr)",line=6,side=1,cex=4)
text(x = -1.2, y = 2.2,
     labels = expression("Speciation rate (species Ma"^{-1} * "capita"^{-1} * ")"),
     adj = c(1, 1), srt = 90, cex = 2.5)
par(new=TRUE, mgp = c(0, 1, 0))
x <- plot.bammdata(best, lwd=2.5,spex = "netdiv",pal = "PiYG")
addBAMMshifts(best,cex = 3.5)
addBAMMlegend(x, location = 'right',nTicks = 1, side = 4,longFrac = 0.25, axisOffset = 0.002,cex.axis = 3)
par(new=TRUE)
plot(1, type="n", xlim=c(max(rtt$times), 0), ylim=range(c(smoothingSpline_tm$y, smoothingSpline_co2$y)), axes=FALSE, xlab="", ylab="")
legend(x = 69, y = 2.3, legend=c("Temperature", "CO2"), 
       col=c("#c04851", "black"), lty=5, lwd=3, 
       cex=3, bty="n")
dev.off()


#=====================================================================

#上下排版
pdf("./results/Fabaceae_best_diversification_shift_speciation_tm_co2_final.pdf", height = 62, width = 42)

# 先控制画图范围
par(fig=c(0,1,0.48,1), new=FALSE, mgp=c(0,2,2), oma=c(8,15,3,6))

# 第一个plot
plot(smoothingSpline_tm, col='#FF0000', axes=F, xlim=c(max(rtt$times),0), type="l", lty=5, lwd=5, xlab="", ylab="")
axis(2,line=0, cex.axis=5,lwd=6,lwd.ticks = 6,tck=-0.008)
mtext("Temperature (°C)", line=8, side=2, cex=6, col="black")
title(main="Best Diversification Shifts (speciation)", font.main=1, cex.main=5)
text(x=-1.2, y=28.5,
     labels=expression("speciation rate (species Ma"^{-1} * "capita"^{-1} * ")"),
     adj=c(1,1), srt=90, cex=3.5)
par(fig=c(0,1,0.48,1),new=TRUE)
x <- plot.bammdata(best, lwd=2.5, spex="s")
addBAMMshifts(best, cex=5,par.reset=FALSE)
addBAMMlegend(x, location='right',nTicks=1, side=4,shortFrac = 0.018,longFrac=0.28, axisOffset=0.0025, cex.axis=4)

par(new=TRUE)
plot(1, type="n", xlim=c(max(rtt$times),0), ylim=range(c(smoothingSpline_tm$y, 0)), axes=FALSE, xlab="", ylab="")
legend(x=72, y=28, legend=c("Temperature", "CO2"), col=c("#c04851", "black"), lty=5, lwd=5, cex=5, bty="n")

# 先控制画图范围
par(fig=c(0,1,0,0.52), new=TRUE, mgp=c(0,2,2), oma=c(8,15,3,6))

# 第一个plot
par(fig=c(0,1,0,0.52),new=TRUE)
plot(smoothingSpline_co2_log2, col='black', axes=F, xlim=c(max(rtt$times),0), type="l", lty=5, lwd=5, xlab="", ylab="")
axis(2, line=0, cex.axis=5,at=seq(8, 10, by=1),labels=round(seq(8, 10, by=1), 1),lwd=6,lwd.ticks = 6,tck=-0.008)
axis(1, line=0, cex.axis=5, padj=0.8,lwd=6,lwd.ticks = 6,tck=-0.008)
mtext(expression(log[2](CO[2]~ppm)), line=8, side=2, cex=6, col="black")
mtext("Time before present (Myr)",line=9,side=1,cex=6)

par(fig=c(0,1,0,0.52),new=T)
x <- plot.bammdata(best, lwd=2.5, spex="s")
par(fig=c(0,1,0,0.5),new=T)
addBAMMshifts(best, cex=5,par.reset=FALSE)

dev.off()







#画圆形图=================================


#给系统发育属标注属级分类
#数据处理，标注好书上各个分支对应的亚科

tipname <- as.data.frame(new_fab$tip.label)
colnames(tipname) <- "taxon_name"
tipname$taxon_name <- sub("(.*)_.*", "\\1", tipname$taxon_name)
tipname$taxon_name <- gsub("_GCA", "", tipname$taxon_name)

new_fab$tip.label <- sub("(.*)_.*", "\\1", new_fab$tip.label)
new_fab$tip.label <- gsub("_GCA", "", new_fab$tip.label)


subname <- read.csv("Fabaceae_subfam.wcvp.accepted_240521.csv")
subname$taxon_name <- gsub(" ", "_", subname$taxon_name)

tip_subname <- merge(tipname,subname,by="taxon_name",all.x = T)
#write.csv(tip_subname,"tip_subname.csv")
# tip_subname <- read.csv("tip_subname.csv")

#生成分组文件
group_file <- tip_subname[,c("taxon_name","subfamily")]
colnames(group_file) <- c("taxon_name","subfamily")
# group_file$genus <- gsub(" ", "_", group_file$genus)

write.csv(group_file,"group_file.csv")

#写出再重新读入，我也不知为啥要这样
group_file <- read.csv("group_file.csv",header = T,row.names = 1)

# 按类分组
groupInfo <- split(row.names(group_file), group_file$subfamily)

# 将分组信息添加到树中
# Fab <- groupOTU(new_fab, groupInfo)

df4 <- as.data.frame(tip_subname$subfamily)
rownames(df4) <- gsub(" ","_",tip_subname$taxon_name)
df4$label <- rownames(df4)
colnames(df4) <- c("group","label")

library(ggtree)
library(ggtreeExtra)
library(ggplot2)

col1 <- c("#DC143C","#9400D3","#7B68EE","#0000FF","#48D1CC","#00FF7F","#FFFF00")
col1 <- c("#66C2A5", "#FC8D62", "#8DA0CB", 
          "#E78AC3", "#A6D854", "#FFD92F", "#E5C494")


# 确保 df4$label 和 Fab$tip.label 一致
df4 <- df4[match(Fab$tip.label, df4$label), ]
df4$group <- as.factor(df4$group)

#填充NA值
# write.csv(df4,"./results/df4.csv")
df4 <- read.csv("./results/df4.csv")


# 绘制基本扇形树图
circ <- ggtree(new_fab, layout = "fan", open.angle = 7) + # 增大 open.angle 以避免拥挤
  geom_fruit(
    data = df4,
    geom = geom_tile,
    mapping = aes(y = label, fill = group),
    offset = 0.05, # 调整 offset 以避免重叠
    width = 2
  )+
  scale_fill_manual(values = col1) +
  theme(
    legend.position.inside = c(0.15, 0.9),
    legend.title = element_blank(),
    legend.key.size = unit(100, "pt"),
    legend.text = element_text(size = 80)
  )


pdf("./results/Fabaceae_best_diversification_shift_species_fan_tree.pdf", height = 40, width = 40)
print(circ)
dev.off()




#LTT
# 从系统发育树提取 LTT 数据（阶梯图专用）
ltt_data <- ltt.plot.coords(new_fab, backward = TRUE, type = "S")
df <- data.frame(Time = -ltt_data[,1], Lineages = ltt_data[,2]) 

# 使用 geom_step() 保留阶梯状折线
p <- ggplot(df, aes(x = Time, y = Lineages)) +
  geom_step(color = "#2C3E50", size = 1) +
  labs(
    x = "Age (Ma)",
    y = "Extant lineages"
    # title = "Lineages Through Time"
  ) +
  scale_x_reverse() +
  theme_classic(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    # plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.title = element_text( size = 14),
    axis.text = element_text(size = 12)
  )

print(p)



pdf("./results/Fabaceae_best_diversification_shift_extinction_fan_tm_co2.pdf", height = 40, width = 40)
par(new=TRUE, mgp = c(0, 1, 0),oma=c(3,3,3,5))
x <- plot.bammdata(best,method="polar",
                   lwd=2.5,
                   vtheta=7,
                   rbf=0.01,
                   spex = "e",
                   pal = "BrBG")
par(new=TRUE, mgp = c(0, 1, 0),oma=c(3,3,3,5))
addBAMMshifts(best,method="polar",cex = 5)
addBAMMlegend(x, location = 'right',nTicks = 1, side = 4,shortFrac=0.01,longFrac = 0.2, axisOffset = 0.002,cex.axis = 3)
mtext(expression("extinction rate (species Ma"^{-1} * "capita"^{-1} * ")"), side = 2, line = 1, cex = 3)
par(fig = c(0.43, 0.65, 0.43, 0.62),mgp = c(4.2, 2, 0),mar=c(6,6,1.5,1),lwd = 3,new = TRUE)
# Create step-like LTT plot
old_par <- par(no.readonly = TRUE)
plot(time, lineages, 
     type = "s",  # Step-like plot
     xlab = "Ago (Ma)", 
     ylab = "Extant Lineages", 
     main = "Lineages Through Time", 
     col = "#2C3E50", 
     lwd = 3,  # Line width
     font.main = 1,  # Bold title
     font.lab = 1,   # Bold axis labels
     cex.main = 2.3,  # Title size
     cex.lab = 2.3,   # Axis label size
     cex.axis = 2.3,  # Axis text size
     bty = "L",  # Frame with only bottom (x) and left (y) lines
     xlim = c(max(time), min(time)),
     xaxp = c(min(time), max(time), 5))  # Suppress default x-axis
par(old_par)
dev.off()




par(fig = c(0.45, 0.65, 0.45, 0.65),oma=c(4,4,3,5), new = TRUE)
# Create step-like LTT plot
par(mgp = c(4,2,0),oma=c(4,4,3,5), new = TRUE)
plot(time, lineages, 
     type = "s",  # Step-like plot
     xlab = "Ago (Ma)", 
     ylab = "Extant Lineages", 
     main = "Lineages Through Time", 
     col = "#2C3E50", 
     lwd = 4,  # Line width
     font.main = 2,  # Bold title
     font.lab = 2,   # Bold axis labels
     cex.main = 3,  # Title size
     cex.lab = 3,   # Axis label size
     cex.axis = 3,  # Axis text size
     bty = "L",  # Frame with only bottom (x) and left (y) lines
     xlim = c(max(time), min(time))
     # xaxt = "n"
     )  # Suppress default x-axis



